/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionDonsWindow (void);
GtkWidget* create_userAdministrationWindow (void);
GtkWidget* create_editUserWindow (void);
GtkWidget* create_gestionFichesWindow (void);
GtkWidget* create_averageMoyWindow (void);
GtkWidget* create_listeFichesDonneurWindow (void);
GtkWidget* create_deletePopupWindow (void);
GtkWidget* create_advancedSettingsPopupWindow (void);
GtkWidget* create_ajouter_rdvmc (void);
GtkWidget* create_MenuPrincipalmc (void);
GtkWidget* create_Gestion_rdvmc (void);
GtkWidget* create_modifier_rdvmc (void);
GtkWidget* create_afficher_rdvmc (void);
GtkWidget* create_authentificationWindow (void);
GtkWidget* create_adminWindow (void);
GtkWidget* create_settingsUserWindow (void);
GtkWidget* create_editCinPopupWindow (void);
GtkWidget* create_enterCinPopupWindow (void);
GtkWidget* create_editPasswordPopupWindow (void);
GtkWidget* create_enterPasswordPopupWindow (void);
GtkWidget* create_editEtsWindow (void);
GtkWidget* create_enterCin_resetPasswordPopupWindow (void);
GtkWidget* create_suppression_rdvmc (void);
GtkWidget* create_mainMenuPopupWindow (void);
GtkWidget* create_logoutPopupWindow (void);
GtkWidget* create_settingsPopupWindow (void);
GtkWidget* create_confirmationPopupWindow (void);
GtkWidget* create_editBloodRequestWindow (void);
GtkWidget* create_calendarDialog_manage_bloodRequest (void);
