/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int main (int argc, char *argv[])
{
  GtkWidget *gestionDonsWindow;
  GtkWidget *userAdministrationWindow;
  GtkWidget *editUserWindow;
  GtkWidget *gestionFichesWindow;
  GtkWidget *averageMoyWindow;
  GtkWidget *listeFichesDonneurWindow;
  GtkWidget *deleteEtsPopupWindow;
  GtkWidget *advancedSettingsWindow;
  GtkWidget *ajouter_rdvmc;
  GtkWidget *MenuPrincipalmc;
  GtkWidget *Gestion_rdvmc;
  GtkWidget *modifier_rdvmc;
  GtkWidget *afficher_rdvmc;
  GtkWidget *authentificationWindow;
  GtkWidget *adminWindow;
  GtkWidget *settingsAdminWindow;
  GtkWidget *leaveSettingsAdminPopupWindow;
  GtkWidget *editCinPopupWindow;
  GtkWidget *enterCinPopupWindow;
  GtkWidget *editPasswordPopupWindow;
  GtkWidget *enterPasswordPopupWindow;
  GtkWidget *editEtsWindow;
  GtkWidget *enterCin_resetPasswordPopupWindow;
  GtkWidget *suppression_rdvmc;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  
  authentificationWindow = create_authentificationWindow ();
  gtk_widget_show (authentificationWindow);

  gtk_main ();
  return 0;
}

